import { toSlug } from './projects';

const coursesDatabase = [
  {
    id: 1,
    company: 'DKM & J. Soares Consultoria e Assessoria Empresarial',
    link: '',
    period: 'out/2005',
    title: 'Certificação de auditor interno ISO 9001:2000',
    description: ['ISO 9001', 'Auditoria Interna'],
    extraProjects: [],
  },
  {
    id: 2,
    company: 'ESPM Escola Superior de Propaganda e Marketing',
    link: 'https://www.espm.br',
    period: 'mai/2008',
    title: 'Programa Intensivo de Marketing',
    description: [
      'Estratégias de Marketing',
      'Marketing Editorial',
      'Planejamento de Marketing',
    ],
    extraProjects: [],
  },
  {
    id: 3,
    company: 'Certiprof',
    link: 'https://certiprof.com/pt',
    period: 'jan/2019',
    title: 'Scrum Foundation Professional Certificate (SFPC)',
    description: ['Scrum', 'Métodos Ágeis'],
    extraProjects: [],
  },
  {
    id: 4,
    company: 'Caelum | Alura',
    link: 'https://www.alura.com.br',
    period: 'dez/2020 ~ jan/2021',
    title: 'Desenvolvimento Web com JavasScript',
    description: [
      'Desenvolvimento de front-end',
      'CSS3',
      'HTML5 Semântico',
      'Web design responsivo',
      'JavaScript',
      'Consumo de API',
      'PWA (Progressive Web App)',
    ],
    extraProjects: [],
  },
  {
    id: 5,
    company: 'Digital House Brasil | Rocketseat',
    link: 'https://www.rocketseat.com.br',
    period: 'jun/2022 ~ mar/2023',
    title: 'Desenvolvimento Web Fullstack com JavasScript',
    description: [
      'React.js',
      'Desenvolvimento back-end',
      'SQL',
      'MVC ',
      'Node.js',
      'Express.js',
      'Sequelize.js',
      'EJS',
      'Consumo de API Backend',
      'GitFlow ',
      'GitHub',
      'Gestão de equipes',
      'Programação pareada ',
      'Gestão de tempo',
      'Gestão de projetos',
      'E-Commerce',
      'Scrum',
      'Metodologias ágeis',
    ],
    extraProjects: ['"DhGeek-E-commerce Disney"'],
  },
  {
    id: 6,
    company: 'Ada.tech',
    link: 'https://ada.tech',
    period: 'jan/2025',
    title: 'Front-end com React.js',
    description: [
      'React.js',
      'Programação orientada a objetos (POO)',
      'CSS Modules',
      'Styled Components',
      'React Hooks',
      'TypeScript',
      'Redux',
      'SASS',
    ],
  },
  {
    id: 7,
    company: 'Conquer',
    link: 'https://escolaconquer.com.br',
    period: 'jan/2023 ~ atualmente',
    title: 'Soft-skills e Produtividade',
    description: ['Relações humanas', 'Produtividade inteligente'],
  },
  {
    id: 8,
    company: 'Alura',
    link: 'https://www.alura.com.br',
    period: 'jan/2023 ~ atualmente',
    title: 'IA, soft-skills e front-end',
    description: [
      'Hábitos',
      'Foco',
      'Produtividade',
      'IA Generativa',
      'CSS Avançado',
    ],
  },
];

export const coursesList = coursesDatabase.map((courses) => {
  const slug = toSlug(courses.company);

  return {
    ...courses,
    slug,
    brand: `/brands/${slug}.png`,
  };
});
