import { lazy } from 'react';

const Home = lazy(() => import('@/pages/Home'));
const About = lazy(() => import('@/pages/About'));
const Portfolio = lazy(() => import('@/pages/Portfolio'));
const Contact = lazy(() => import('@/pages/Contact'));

export const pagesMetadata = {
  home: {
    path: '/',
    component: Home,
    title: 'Home',
    description:
      'Portfólio profissional de Danilo Batista, desenvolvedor front-end e designer gráfico.',
    keywords: [
      'Danilo Batista',
      'portifólio de Danilo Batista',
      'desenvolvedor front-end',
      'designer gráfico',
      'front-end developer',
      'projetos digitais',
      'web design',
      'design criativo',
      'react',
      'sass',
      'css',
      'html',
      'responsividade',
      'javascript',
    ],
    ogImage: '/images/og-home.png',
    index: true,
  },
  about: {
    path: 'sobre-mim',
    component: About,
    title: 'Sobre Mim',
    description:
      'Conheça a história de Danilo Batista: designer gráfico e desenvolvedor front-end com experiência em embalagens, quadrinhos e projetos digitais.',
    keywords: [
      'Danilo Batista',
      'sobre Danilo Batista',
      'desenvolvedor front-end',
      'experiência profissional',
      'designer gráfico',
      'front-end developer',
      'projetos digitais',
      'web design',
      'design criativo',
      'embalagens',
      'quadrinhos',
      'criatividade',
      'react',
      'sass',
      'css',
      'html',
      'responsividade',
      'javascript',
    ],
    ogImage: '/images/og-sobre-mim.png',
  },
  portfolio: {
    path: 'portifolio',
    component: Portfolio,
    title: 'Portifólio',
    description:
      'Explore os destaques do portfólio de Danilo Batista — projetos front-end criativos desenvolvidos em React, JavaScript, HTML e CSS, com forte base em design gráfico.',
    keywords: [
      'Danilo Batista',
      'portifólio de Danilo Batista',
      'desenvolvedor front-end',
      'experiência profissional',
      'designer gráfico',
      'front-end developer',
      'projetos digitais',
      'web design',
      'design criativo',
      'embalagens',
      'quadrinhos',
      'criatividade',
      'landing page',
      'e-commerce',
      'react',
      'sass',
      'css',
      'html',
      'responsividade',
      'javascript',
    ],
    ogImage: '/images/og-portfolio.png',
  },
  contact: {
    path: 'contato',
    component: Contact,
    title: 'Contato',
    description:
      'Entre em contato com Danilo Batista — desenvolvedor front-end e designer gráfico. Vamos conversar sobre como cocriar soluções digitais com criatividade e impacto.',
    keywords: [
      'Danilo Batista',
      'contato Danilo Batista',
      'mensagem para Danilo Batista',
      'contratar Danilo Batista',
      'desenvolvedor front-end',
      'experiência profissional',
      'designer gráfico',
      'front-end developer',
      'projetos digitais',
      'web design',
      'design criativo',
      'embalagens',
      'quadrinhos',
      'criatividade',
      'landing page',
      'e-commerce',
      'react',
      'sass',
      'css',
      'html',
      'responsividade',
      'javascript',
      'cocriação',
      'colaboração multidisciplinar',
    ],
    ogImage: '/images/og-contact.png',
  },
};
